/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserPreferencesRouteImport } from './routes/user/preferences'
import { Route as RecipesScribeRouteImport } from './routes/recipes/scribe'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthResetpasswordRouteImport } from './routes/auth/resetpassword'
import { Route as AuthForgotpasswordRouteImport } from './routes/auth/forgotpassword'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPreferencesRoute = UserPreferencesRouteImport.update({
  id: '/user/preferences',
  path: '/user/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesScribeRoute = RecipesScribeRouteImport.update({
  id: '/recipes/scribe',
  path: '/recipes/scribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetpasswordRoute = AuthResetpasswordRouteImport.update({
  id: '/auth/resetpassword',
  path: '/auth/resetpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotpasswordRoute = AuthForgotpasswordRouteImport.update({
  id: '/auth/forgotpassword',
  path: '/auth/forgotpassword',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/recipes/scribe': typeof RecipesScribeRoute
  '/user/preferences': typeof UserPreferencesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/recipes/scribe': typeof RecipesScribeRoute
  '/user/preferences': typeof UserPreferencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/recipes/scribe': typeof RecipesScribeRoute
  '/user/preferences': typeof UserPreferencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgotpassword'
    | '/auth/resetpassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/recipes/scribe'
    | '/user/preferences'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgotpassword'
    | '/auth/resetpassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/recipes/scribe'
    | '/user/preferences'
  id:
    | '__root__'
    | '/'
    | '/auth/forgotpassword'
    | '/auth/resetpassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/recipes/scribe'
    | '/user/preferences'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotpasswordRoute: typeof AuthForgotpasswordRoute
  AuthResetpasswordRoute: typeof AuthResetpasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  RecipesScribeRoute: typeof RecipesScribeRoute
  UserPreferencesRoute: typeof UserPreferencesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/preferences': {
      id: '/user/preferences'
      path: '/user/preferences'
      fullPath: '/user/preferences'
      preLoaderRoute: typeof UserPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/scribe': {
      id: '/recipes/scribe'
      path: '/recipes/scribe'
      fullPath: '/recipes/scribe'
      preLoaderRoute: typeof RecipesScribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/resetpassword': {
      id: '/auth/resetpassword'
      path: '/auth/resetpassword'
      fullPath: '/auth/resetpassword'
      preLoaderRoute: typeof AuthResetpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgotpassword': {
      id: '/auth/forgotpassword'
      path: '/auth/forgotpassword'
      fullPath: '/auth/forgotpassword'
      preLoaderRoute: typeof AuthForgotpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotpasswordRoute: AuthForgotpasswordRoute,
  AuthResetpasswordRoute: AuthResetpasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  RecipesScribeRoute: RecipesScribeRoute,
  UserPreferencesRoute: UserPreferencesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
